### ISSUE TITLE
PHP Fatal error:  Class 'Elgg\Application' not found

### ISSUE THREAD

**Issue by dipenpatel235** [juho-jaakkola/elgg-pusher#11]
php -f /usr/local/nginx/html/elgg/mod/pusher/push-server.php
PHP Fatal error:  Class 'Elgg\Application' not found in /usr/local/nginx/html/elgg/mod/pusher/push-server.php on line 7
PHP Stack trace:
PHP   1. {main}() /usr/local/nginx/html/elgg/mod/pusher/push-server.php:0

**Comment by dipenpatel235** [comment]
Ok...finally i have fixed using
replace Elgg\Application by elgg 1 related API
$elgg = require_once('../../engine/start.php');

Thanks

**Comment by juho-jaakkola** [comment]
IIRC the plugin currently works only if it has been installed as a [composer dependency](https://github.com/elgg/starter-project), so that the `autoload.php` of the site root knows where to find `Elgg\Application`.
