### ISSUE TITLE
elgg 2.2.2 ERROR: 'create, member_of_site' event is no longer triggered.

### ISSUE THREAD

**Issue by dipenpatel235** [juho-jaakkola/elgg-pusher#13]
php -f push-server.php

ERROR: 'create, member_of_site' event is no longer triggered. Update your event registration to use 'create, relationship'
ERROR: 'delete, member_of_site' event is no longer triggered. Update your event registration to use 'delete, relationship'

**Comment by dipenpatel235** [comment]
ok..i have fixed that inside ..........mod/profile_manager/start.php

replace member_of_site by relationship

```
    // site join event handler
    elgg_register_event_handler("create", "relationship", "profile_manager_create_member_of_site");

    // always cleanup
    elgg_register_event_handler("delete", "relationship", "profile_manager_delete_member_of_site");
```

**Comment by juho-jaakkola** [comment]
FYI, this has already been fixed in the official profile_manager plugin: https://github.com/ColdTrick/profile_manager/blob/master/start.php#L77-L78
