### ISSUE TITLE
i just set this up in fedora 23 and there is no 'nohub' command

### ISSUE THREAD

**Issue by propertunist** [juho-jaakkola/elgg-pusher#3]
i did see your code working in fedora in the past, but now when i came to set this up i discovered that there is no command available in fedora 23 called 'nohub'. i was not able to install it or find out much about it online. do you have any tip for me on that?
also, i wasn't sure what port to assign for the public web port socket.. i used 8081.

**Comment by propertunist** [comment]
so i think that maybe 'nohub' is meant to be the command 'nohup' - is that right?
i also saw the port 5555 listed here: https://github.com/juho-jaakkola/elgg-live_notifier/blob/master/start.php
is that the one i need to use?

**Comment by juho-jaakkola** [comment]
That is a typo. It should be "nohup" as in "No hang up". Basically you can use any software, configuration, or hack that allows you to make the push server run as a background process. The `nohup` command is just one way to achieve that.

> i also saw the port 5555 listed. is that the one i need to use?

No, that port is not used by the websockets. That is just for internal server communication (e.g. notifier tells the push server to send a new notification message.)

For the websocket connection you can use whichever port you like.

**Comment by propertunist** [comment]
i see, ok. i set both the sockets to 8082 and flushed the caches. i used this command in the terminal:

```
nohup /usr/bin/php -f /mysite/mod/pusher/push-server.php
```

the outcome in the terminal was:

```
nohup: ignoring input and appending output to ‘nohup.out’
```

the output in the browser console is:

```
Firefox can't establish a connection to the server at ws://dev.ureka.org:8082/.
```

**Comment by Daltonstudio** [comment]
Can you check the nohup.out file for errors?

**Comment by Daltonstudio** [comment]
I had the same problem and seemed I had a composer problem installing the vendor folder.

**Comment by propertunist** [comment]
oh ok, i didn't realise there was  an output file to check. yes, i am seeing the same error:

```
Warning: require(/mysite/mod/pusher/vendor/autoload.php): failed to open stream: No such file or directory in /mysite/mod/pusher/push-server.php on line 4
```

the vendor folder does not exist.

**Comment by propertunist** [comment]
so i realised that the first require in the push-server.php file is intended to launch the main elgg autoloader and that the 2nd one is either a spurious command or refers to a vender folder that is missing from this plugin. i commented out the 2nd require and now the content of the output file is:

```
<!DOCTYPE html>
<html>
    <head>
        <title>oops.. a serious error has occurred.</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <style type="text/css">

        body {
            text-align:left;
            margin:0;
            padding:0;
            background: #000000;
            font: 80%/1.5  "Lucida Grande", Verdana, sans-serif;
            color: #eeeeee;
        }
        p {
            margin: 0px 0px 15px 0;
        }
        h1 {color: #f60;}
        #elgg-wrapper {
            width:570px;
            margin:auto;
            padding:10px 40px;
            margin-bottom:40px;
            margin-top:20px;
            border-bottom: 1px solid #666666;
            background: rgba(25, 25, 25, 0.66);
            border-top: 2px solid rgba(138, 138, 138, 0.5);
            border-radius: 20px; 
            border-bottom: 2px solid rgba(39, 39, 39, 0.5)
        }
        .elgg-messages-exception {
            background:#191919;
            display:block;
            padding:10px;
        }
        </style>

    </head>
    <body>
    <div id="elgg-wrapper">
        <h1>oops.. a serious error has occurred.</h1>

<p class="elgg-messages-exception">
    <span title="Unrecoverable Error">
        an unrecoverable error has occurred and has been logged. you can contact the site administrator with the following information:     <br /><br />
        Exception #1466631950.
    </span>
</p>
    </div>
    </body>
</html>
```

and i am seeing this in the browser console:

```
Firefox can't establish a connection to the server at ws://dev.ureka.org:8082/.
```

**Comment by juho-jaakkola** [comment]
You must run `composer install` command in the plugin folder. That step is missing from the instructions.

**Comment by propertunist** [comment]
aha, ok. i ran composer and get some errors about guzzle packages being abandoned. i restarted the push server and flushed the caches - with the result that i still see the browser console error about not being able to connect to the server. the nohup output file now includes this line at the bottom:

```
No configuration file found at /root/.esmtprc or /etc/esmtprc
```

**Comment by Daltonstudio** [comment]
In my case it was a composer bug, I updated and it installed all correctly and its working.
Anyway, not the same problem it seems, so sorry for interrupting.

That error you see has to do with eSMTP, which is used by your server to deliver e-mails, more a server issue it seems.

**Comment by Daltonstudio** [comment]
@propertunist : Have you made sure the port your trying to connect to is accessible on your server?

**Comment by propertunist** [comment]
i am not running this on a remote server, everything is on my local machine and it doesn't have an email server installed or configured - so the issue is not directly connected to a misconfigured email server.

**Comment by propertunist** [comment]
i am running composer 1.1.2 here, so i think that is the latest version and shouldn't be experiencing the bug you mentioned @Daltonmedia

**Comment by propertunist** [comment]
i just noticed that the console shows an error type of 413 - request entity too large
this page says to configure nginx directives to overcome the issue - however, i had already set these values to be in the gigabyte range:
http://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by juho-jaakkola** [comment]
How about we move this discussion to the Technical support group at the community?

Also, don't be afraid to create a new discussion for each individual topic ("how to use nohup", "I'm getting error X with push server", "which port should I use with the push server", etc).

**Comment by propertunist** [comment]
i am not currently receiving any email notifications from the elgg community and my attempt to get assistance with resolving it didn't get me anywhere - so i have no choice but to use github for issues presently.
